baseURL = 'https://maxwinthrop.co.uk/'
languageCode = 'en-gb'
title = 'A little learning'

[params]
LinkedIn = 'https://uk.linkedin.com/in/max-winthrop-50914b28'

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 10

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'